// Generates one Code Connect template per UI3 icon that has a matching SVG in
// src/icons, so nested icons (e.g. Button's ↪ Icon) resolve to kit imports.
// Based on https://github.com/figma/code-connect/blob/main/cli/scripts/README.md
//
// Run from the package root: `npm run figma:icons` (reads FIGMA_ACCESS_TOKEN from .env).
import { client } from '@figma/code-connect'
import fs from 'node:fs'
import path from 'node:path'

const ICONS_PAGE = 'https://www.figma.com/design/6dJFbL7SDC7kkS1fu3AHH6/UI3?node-id=1-530873'
const OUT_DIR = 'figma/icons'

// icon.24.star.small → Icon24StarSmall
const toIdentifier = (name) =>
  name
    .split(/[.\-_ ]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

const components = await client.getComponents(ICONS_PAGE)

fs.rmSync(OUT_DIR, { recursive: true, force: true })
fs.mkdirSync(OUT_DIR, { recursive: true })

const written = new Set()
const missingSvg = []

for (const { name, id, type } of components) {
  const match = name.match(/^icon\.(16|24)\./)
  if (type !== 'COMPONENT' || !match) continue

  const svg = `src/icons/${match[1]}/${name}.svg`
  if (!fs.existsSync(svg)) {
    missingSvg.push(name)
    continue
  }
  if (written.has(name)) continue
  written.add(name)

  const identifier = toIdentifier(name)
  fs.writeFileSync(
    path.join(OUT_DIR, `${name}.figma.ts`),
    `// Generated by figma/scripts/import-icons.mjs — do not edit.
// url=<UI3_FILE>?node-id=${id.replace(':', '-')}
// source=${svg}
// component=${identifier}
import figma from 'figma'

export default {
  example: figma.code\`${identifier}\`,
  imports: ["import ${identifier} from 'figma-ui3-kit-svelte/${svg}'"],
  id: '${name}',
  metadata: { nestable: true },
}
`,
  )
}

console.log(`Wrote ${written.size} icon templates to ${OUT_DIR}/`)
if (missingSvg.length) {
  console.log(`Skipped ${missingSvg.length} Figma icons with no SVG in src/icons:`)
  console.log(missingSvg.map((n) => `  ${n}`).join('\n'))
}
